node {
    def mvnHome

    stage('Preparation') {
        git 'https://github.com/wardvia ene/java-demo.git'
        // Get the Maven tool.
        mvnHome = t 'M3'
    }
    stage('Build') {
        // Run the maven build
        if (isUnix()) {
            
        }
    }
}