apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonar-data
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
  path: /data/sonar-data
  type: DirectoryOrCreate