apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonar-extension-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: /data/sonar-extension
    type: DirectoryOrCreate