apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonar-extension
  namespace: default
spec:
  storageClassName: standard
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi