apiVersion: v1
kind: Service
metadata:
  name: postgresdb-service
  labels:
    app: sonarqube
    db: postgres
spec:
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
  selector:
    db: postgres
  type: ClusterIP